export function generateApiFileTemplate(
  websiteUrl: string,
  schema: Record<string, unknown>,
  instructions: string,
  refinedPrompt: string
): string {
  const schemaStr = JSON.stringify(schema, null, 2);
  const hostname = (() => {
    try {
      return new URL(websiteUrl).hostname;
    } catch {
      return websiteUrl;
    }
  })();
  const className = hostname
    .replace(/[^a-zA-Z0-9]/g, "_")
    .replace(/^_+|_+$/g, "")
    .split("_")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");

  return `/**
 * Auto-generated Scraper Script for: ${websiteUrl}
 * Generated by Scrapex — ${new Date().toISOString()}
 *
 * HOW TO RUN:
 *   npm install playwright
 *   npx playwright install chromium
 *   npx ts-node scraper.ts
 *
 * Or compile first:
 *   npx tsc --target ES2020 --module CommonJS --esModuleInterop true scraper.ts
 *   node scraper.js
 *
 * Instructions: ${instructions}
 *
 * Specification:
 * ${refinedPrompt.split("\n").join("\n * ")}
 */

import { chromium, Browser, Page } from "playwright";

// ─── Data Schema ─────────────────────────────────────────────────────────────
// Represents one extracted record. The scraper returns an array of these.

export interface ScrapedItem {
${buildInterfaceFields(schema)}
}

// ─── Configuration ────────────────────────────────────────────────────────────

const CONFIG = {
  startUrl: "${websiteUrl}",
  /** Delay between page loads in milliseconds — increase if you hit rate limits */
  requestDelay: 1500,
  /** Maximum pages to scrape (set to Infinity to scrape all pages) */
  maxPages: 10,
  /** Headless mode — set to false to watch the browser */
  headless: true,
} as const;

const SCHEMA_HINT = ${schemaStr} as const;

// ─── Scraper ──────────────────────────────────────────────────────────────────

export class ${className}Scraper {
  private browser: Browser | null = null;
  private page: Page | null = null;
  private results: ScrapedItem[] = [];

  async init(): Promise<void> {
    this.browser = await chromium.launch({
      headless: CONFIG.headless,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });
    const context = await this.browser.newContext({
      userAgent:
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
        "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      viewport: { width: 1280, height: 900 },
    });
    this.page = await context.newPage();
  }

  /** Navigate to a URL with retry logic */
  private async goto(url: string, retries = 3): Promise<void> {
    for (let attempt = 1; attempt <= retries; attempt++) {
      try {
        await this.page!.goto(url, { waitUntil: "networkidle", timeout: 30_000 });
        return;
      } catch (err) {
        if (attempt === retries) throw err;
        console.warn(\`[Scraper] Attempt \${attempt} failed, retrying in \${attempt * 2}s…\`);
        await sleep(attempt * 2000);
      }
    }
  }

  /** Extract items from the current page */
  private async extractItems(): Promise<ScrapedItem[]> {
    await this.page!.waitForLoadState("domcontentloaded");

    const items = await this.page!.evaluate((schema) => {
      // ── Find repeating item containers ────────────────────────────────────
      const containers = Array.from(
        document.querySelectorAll(
          "article, [class*='card'], [class*='item'], [class*='product'], " +
          "[class*='result'], [class*='listing'], li, tr"
        )
      ).filter((el) => el.children.length > 0 && el.textContent!.trim().length > 0);

      const data: Record<string, unknown>[] = [];

      if (containers.length > 0) {
        containers.forEach((container) => {
          const entry: Record<string, unknown> = {};
          for (const key of Object.keys(schema)) {
            // Try common patterns based on the field name
            const selectors = [
              \`[class*='\${key}']\`,
              \`[data-\${key}]\`,
              \`.\${key}\`,
              \`#\${key}\`,
              \`[itemprop='\${key}']\`,
            ];
            for (const sel of selectors) {
              const el = container.querySelector(sel);
              if (el) {
                entry[key] =
                  el.getAttribute("href") ??
                  el.getAttribute("src") ??
                  el.getAttribute("content") ??
                  el.textContent?.trim() ??
                  "";
                break;
              }
            }
            if (!(key in entry)) entry[key] = "";
          }
          data.push(entry);
        });
      } else {
        // Single-record page fallback
        const entry: Record<string, unknown> = {};
        for (const key of Object.keys(schema)) {
          const selectors = [
            \`[class*='\${key}']\`,
            \`.\${key}\`,
            \`#\${key}\`,
            \`[data-\${key}]\`,
          ];
          for (const sel of selectors) {
            const el = document.querySelector(sel);
            if (el) {
              entry[key] = el.textContent?.trim() ?? "";
              break;
            }
          }
          if (!(key in entry)) entry[key] = "";
        }
        data.push(entry);
      }

      return data;
    }, SCHEMA_HINT);

    return items as ScrapedItem[];
  }

  /** Find the "next page" URL, or null if no more pages */
  private async getNextPageUrl(): Promise<string | null> {
    return this.page!.evaluate(() => {
      const nextLink = document.querySelector(
        "a[rel='next'], a[aria-label*='next' i], a[class*='next'], " +
        ".pagination a:last-child, [class*='pagination'] a:last-child"
      ) as HTMLAnchorElement | null;
      return nextLink?.href ?? null;
    });
  }

  /** Run the full scrape — navigates, extracts, paginates */
  async scrape(): Promise<ScrapedItem[]> {
    if (!this.page) throw new Error("Scraper not initialized. Call init() first.");

    let currentUrl: string | null = CONFIG.startUrl;
    let pageNum = 0;

    while (currentUrl && pageNum < CONFIG.maxPages) {
      pageNum++;
      console.log(\`[Scraper] Page \${pageNum}: \${currentUrl}\`);

      await this.goto(currentUrl);
      const items = await this.extractItems();
      console.log(\`[Scraper] Extracted \${items.length} item(s) from page \${pageNum}\`);
      this.results.push(...items);

      currentUrl = await this.getNextPageUrl();

      if (currentUrl && pageNum < CONFIG.maxPages) {
        await sleep(CONFIG.requestDelay);
      }
    }

    console.log(\`[Scraper] Done. Total records: \${this.results.length}\`);
    return this.results;
  }

  async screenshot(path: string): Promise<void> {
    await this.page?.screenshot({ path, fullPage: true });
  }

  async close(): Promise<void> {
    await this.browser?.close();
    this.browser = null;
    this.page = null;
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

// ─── Entry Point ──────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const scraper = new ${className}Scraper();
  try {
    await scraper.init();
    const data = await scraper.scrape();

    // Output results to stdout as formatted JSON
    console.log("\\n── Results ───────────────────────────────────");
    console.log(JSON.stringify(data, null, 2));

    // Optionally save screenshot for debugging
    await scraper.screenshot("screenshot.png");
    console.log("\\nScreenshot saved to screenshot.png");
  } finally {
    await scraper.close();
  }
}

main().catch((err) => {
  console.error("[Scraper] Fatal error:", err);
  process.exit(1);
});
`;
}

function buildInterfaceFields(schema: Record<string, unknown>): string {
  return Object.entries(schema)
    .map(([key, value]) => {
      const tsType = inferTsType(value);
      return `  ${key}: ${tsType};`;
    })
    .join("\n");
}

function inferTsType(value: unknown): string {
  if (value === null || value === undefined) return "string";
  if (typeof value === "boolean") return "boolean";
  if (typeof value === "number") return "number";
  if (Array.isArray(value)) {
    if (value.length === 0) return "string[]";
    return `${inferTsType(value[0])}[]`;
  }
  if (typeof value === "object") {
    return "Record<string, unknown>";
  }
  return "string";
}
