export function generateApiFileTemplate(
  websiteUrl: string,
  schema: Record<string, unknown>,
  instructions: string,
  refinedPrompt: string
): string {
  const schemaStr = JSON.stringify(schema, null, 2);
  const hostname = (() => {
    try {
      return new URL(websiteUrl).hostname;
    } catch {
      return websiteUrl;
    }
  })();
  const className = hostname
    .replace(/[^a-zA-Z0-9]/g, "_")
    .replace(/^_+|_+$/g, "")
    .split("_")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");

  return `/**
 * Auto-generated Scraper API for: ${websiteUrl}
 * Generated by AI Scraper — ${new Date().toISOString()}
 *
 * Instructions: ${instructions}
 *
 * Refined prompt:
 * ${refinedPrompt.split("\n").join("\n * ")}
 */

import { chromium, Browser, Page } from "playwright";

// ─── Data Schema ────────────────────────────────────────────────────────────

export interface ScrapedData {
${buildInterfaceFields(schema)}
}

const TARGET_URL = "${websiteUrl}";

const SCHEMA_HINT = ${schemaStr} as const;

// ─── Scraper Class ────────────────────────────────────────────────────────────

export class ${className}Scraper {
  private browser: Browser | null = null;
  private page: Page | null = null;

  async init(): Promise<void> {
    this.browser = await chromium.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });
    this.page = await this.browser.newPage();
    await this.page.setExtraHTTPHeaders({
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
        "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    });
  }

  async scrape(): Promise<ScrapedData[]> {
    if (!this.page) throw new Error("Scraper not initialized. Call init() first.");

    console.log(\`[Scraper] Navigating to \${TARGET_URL}\`);
    await this.page.goto(TARGET_URL, { waitUntil: "networkidle", timeout: 30_000 });

    // Wait for content to load
    await this.page.waitForLoadState("domcontentloaded");

    console.log("[Scraper] Extracting data...");
    const results = await this.page.evaluate((schema) => {
      // ── Dynamic extraction based on schema ──
      const data: Record<string, unknown>[] = [];

      // Find repeating containers (cards, list items, table rows, etc.)
      const containers = document.querySelectorAll(
        "article, [class*='card'], [class*='item'], [class*='product'], li, tr"
      );

      if (containers.length > 0) {
        containers.forEach((container) => {
          const entry: Record<string, unknown> = {};
          for (const key of Object.keys(schema)) {
            // Try common element patterns for each schema key
            const selectors = [
              \`[class*='\${key}']\`,
              \`[data-\${key}]\`,
              \`.\${key}\`,
              \`#\${key}\`,
            ];
            for (const sel of selectors) {
              const el = container.querySelector(sel);
              if (el) {
                entry[key] = el.textContent?.trim() ?? el.getAttribute("href") ?? "";
                break;
              }
            }
            if (!(key in entry)) {
              entry[key] = "";
            }
          }
          data.push(entry);
        });
      } else {
        // Single-page extraction fallback
        const entry: Record<string, unknown> = {};
        for (const key of Object.keys(schema)) {
          const selectors = [
            \`[class*='\${key}']\`,
            \`.\${key}\`,
            \`#\${key}\`,
            \`[data-\${key}]\`,
          ];
          for (const sel of selectors) {
            const el = document.querySelector(sel);
            if (el) {
              entry[key] = el.textContent?.trim() ?? "";
              break;
            }
          }
          if (!(key in entry)) entry[key] = "";
        }
        data.push(entry);
      }

      return data;
    }, SCHEMA_HINT);

    console.log(\`[Scraper] Extracted \${results.length} record(s)\`);
    return results as ScrapedData[];
  }

  async screenshot(path: string): Promise<void> {
    await this.page?.screenshot({ path, fullPage: true });
  }

  async close(): Promise<void> {
    await this.browser?.close();
    this.browser = null;
    this.page = null;
  }
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const scraper = new ${className}Scraper();
  try {
    await scraper.init();
    const data = await scraper.scrape();
    console.log("\\n── Scraped Data ──────────────────────────────");
    console.log(JSON.stringify(data, null, 2));
    await scraper.screenshot("screenshot.png");
    console.log("\\nScreenshot saved to screenshot.png");
  } finally {
    await scraper.close();
  }
}

main().catch(console.error);
`;
}

function buildInterfaceFields(schema: Record<string, unknown>): string {
  return Object.entries(schema)
    .map(([key, value]) => {
      const tsType = inferTsType(value);
      return `  ${key}: ${tsType};`;
    })
    .join("\n");
}

function inferTsType(value: unknown): string {
  if (value === null || value === undefined) return "string";
  if (typeof value === "boolean") return "boolean";
  if (typeof value === "number") return "number";
  if (Array.isArray(value)) {
    if (value.length === 0) return "string[]";
    return `${inferTsType(value[0])}[]`;
  }
  if (typeof value === "object") {
    return "Record<string, unknown>";
  }
  return "string";
}
